// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the 'Update Firebase Project' command.
// See https://firebase.google.com/docs/projects/learn-more#project-id
// for more details about Firebase project IDs.

// The content of this file is not sensitive and can be safely included in your client-side code.
// See https://firebase.google.com/docs/web/setup#config-object for more details.

export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-auth-domain",
  "projectId": "mock-project-id",
  "storageBucket": "mock-storage-bucket",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id",
  "measurementId": "mock-measurement-id"
};
