// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the 'Update Firebase Project' command.
// See https://firebase.google.com/docs/projects/learn-more#project-id
// for more details about Firebase project IDs.

// The content of this file is not sensitive and can be safely included in your client-side code.
// See https://firebase.google.com/docs/web/setup#config-object for more details.

export const firebaseConfig = {
  "projectId": "studio-3017635330-1ac18",
  "appId": "1:846043118353:web:fadd0ab205b072c3b76ab0",
  "apiKey": "AIzaSyCoz5uTGVOEyHF9mkzlmX_63LKM5Tq8TFA",
  "authDomain": "studio-3017635330-1ac18.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "846043118353"
};
